### ISSUE TITLE
locomotivescroll  weird sideeffect

### ISSUE THREAD

**Issue by hellofantastic** [fcisio/gatsby-locomotivescroll-starter#1]
Hey hope all is well.

I already have a gastby site and was looking for interia/smooth scroll to implement and came across the locomotive from spectrum chat for gatsby and you starter.
preface my site already has working parallax which has a handle scroll method which listens for scroll on window (window.addEventListener (''scroll", handScroll ))  

Wondering if you have insight on  how  you Scroll component is implemented that it stops other  components  scroll events from working?

EDIT: just read that for fixed header it needs to be outside of scroll container so thats one down but maybe even makes it trickier to work with as the fixed header on scroll changes still don't work.

**Comment by fcisio** [comment]
Hi @hellofantastic ,
When using Locomotive scroll, the native scroll is not used. Instead, a specified scroll container is animated to simulate the scroll. This is why your existing parallax does not work.

If you want to be using Locomotive scroll, you will need to use their implementation of parallax and other useful options.

For example, you can look at this starter's [Header](https://github.com/fcisio/gatsby-locomotivescroll-starter/blob/master/src/components/header.js) code. It has some essential attributes `data-scroll`, `data-scroll-sticky`, `data-scroll-target`.

For any further questions, I think you would find better help on the actual [Locomotive Scroll](https://github.com/locomotivemtl/locomotive-scroll) repo.

**Comment by hellofantastic** [comment]
Thanks Francis, Appreciate it. On Aug. 2, 2020 3:01 p.m., Francis Champagne <notifications@github.com> wrote:
Hi @hellofantastic ,
When using Locomotive scroll, the native scroll is not used. Instead, a specified scroll container is animated to simulate the scroll. This is why your existing parallax does not work.
If you want to be using Locomotive scroll, you will need to use their implementation of parallax and other useful options.
For example, you can look at this starter's Header code. It has some essential attributes data-scroll, data-scroll-sticky, data-scroll-target.
For any further questions, I think you would find better help on the actual Locomotive Scroll repo.
