### ISSUE TITLE
ERROR #95313 - Building static HTML failed for path "/404/"

### ISSUE THREAD

**Issue by tjzijlstra** [fcisio/gatsby-locomotivescroll-starter#2]
### Summary

When I'm serving the project with gatsby develop all is working fine. But when I try to use the build command I get this error. Stuck in this for days. Any clue how to solve this?

### Expected result

Project should be deployed without errors.

### Actual Result
''PS F:\websitevoor350-concept> gatsby build
success open and validate gatsby-configs - 0.030s
success load plugins - 1.271s
success onPreInit - 0.077s
success delete html and css files from previous builds - 0.010s
success initialize cache - 0.010s
success copy gatsby files - 0.107s
success onPreBootstrap - 0.011s
success createSchemaCustomization - 0.010s
success Checking for changed pages - 0.003s
success source and transform nodes - 0.095s
success building schema - 0.323s
success createPages - 0.012s
success Checking for changed pages - 0.004s
success createPagesStatefully - 0.108s
success update schema - 0.026s
success onPreExtractQueries - 0.002s
success extract queries from components - 0.306s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.153s
success onPostBootstrap - 0.159s
info bootstrap finished - 7.718s
success run static queries - 0.021s - 1/1 46.66/s
success run page queries - 0.023s - 9/9 388.00/s
success write out requires - 0.012s
success Building production JavaScript and CSS bundles - 4.360s
success Rewriting compilation hashes - 0.009s
failed Building static HTML for pages - 1.114s

 ERROR #95313 

Building static HTML failed for path "/404/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]= for the full message 
  or use the non-minified dev environment for full errors and additional helpful warnings.

  - react-dom-server.node.production.min.js:48 a.b.render
    [websitevoor350-concept]/[react-dom]/cjs/react-dom-server.node.production.min.js:48:37

  - react-dom-server.node.production.min.js:44 a.b.read
    [websitevoor350-concept]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18

  - react-dom-server.node.production.min.js:54 renderToString
    [websitevoor350-concept]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:651 Module../.cache/static-entry.js.__webpack_exports__.default
    F:/websitevoor350-concept/public/render-page.js:651:28

  - render-html.js:28 
    [websitevoor350-concept]/[gatsby]/dist/utils/worker/render-html.js:28:36

  - debuggability.js:384 Promise._execute
    [websitevoor350-concept]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [websitevoor350-concept]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [websitevoor350-concept]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:24 
    [websitevoor350-concept]/[gatsby]/dist/utils/worker/render-html.js:24:47

  - util.js:16 tryCatcher
    [websitevoor350-concept]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [websitevoor350-concept]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [websitevoor350-concept]/[bluebird]/js/release/promise_array.js:115:31

  - promise_array.js:79 MappingPromiseArray.init
    [websitevoor350-concept]/[bluebird]/js/release/promise_array.js:79:10

  - map.js:37 MappingPromiseArray._asyncInit
    [websitevoor350-concept]/[bluebird]/js/release/map.js:37:10

  - async.js:97 _drainQueueStep
    [websitevoor350-concept]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [websitevoor350-concept]/[bluebird]/js/release/async.js:86:9

PS F:\websitevoor350-concept> gatsby build

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
  Binaries:
    Node: 12.16.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.135
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.53 => 2.24.53
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-manifest: ^2.4.27 => 2.4.27
    gatsby-plugin-offline: ^3.2.26 => 3.2.26
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.31 => 2.6.31
    gatsby-source-filesystem: ^2.3.27 => 2.3.27
    gatsby-transformer-sharp: ^2.5.14 => 2.5.14
  npmGlobalPackages:
    gatsby-cli: 2.12.89

**Comment by fcisio** [comment]
This doesn't seem to be related to the repo. This is most likely stemming from your codebase.
Since the error say's the issue is coming from the 404 page, you can try to remove it to at least see if that solves the issue.

You can also try a fresh install of this repo, if there's no problem then, it's not related to the repo.

**Comment by tjzijlstra** [comment]
When I remove the 404 page it gives the same error for the next page in the page folder.

I'll try a fresh install tomorrow, and give an update here. Thanks for your fast reply.

**Comment by tjzijlstra** [comment]
I tried a fresh install of this repo and copied all my content back. Works like a charm now. Thanks for this great starter template!

**Comment by fcisio** [comment]
Awesome, glad to hear it worked for you.
If it ever happens again, I would suggest deleting the `.cache` directory.

It should resolve any issues like that one!
