### ISSUE TITLE
Integrating with Intersection observer to "lazy load"

### ISSUE THREAD

**Issue by canadianeagle** [fcisio/gatsby-locomotivescroll-starter#5]
Hello @fcisio 

Thanks so much for your help and advice on the last issue I opened. I have another interesting use case I'm hoping you could help me with.

I'm trying to use IntersectionObserver to improve the performance of a project I built on this starter. To give some background, I want to "lazy-load" multiple sections containing images. I've tried suspense and loadable and neither is working. I'm assuming it's due to locomotive scroll somehow? Any ideas how to get around this?

My way to attempt to get around lazy-loading not working is to use Intersection Observer. I've tried a few different hooks and nothing seems to be working. Basically, the sections act like they're always hidden and never enter the viewport.

I tried an implementation **useIntersection** from "react-use" to no avail.

const intersectionRef = React.useRef(null);
const intersection = useIntersection(intersectionRef, {
    root: null,
    rootMargin: '0px',
    threshold: 1
  });
<section data-scroll-section className="when" id="when" ref={intersectionRef}>
      {intersection && intersection.intersectionRatio < 1
        ? 'Obscured'
        : 'Fully in view'}
</section>

The result for the above is always obscured. 

I would be very grateful for any direction at all. 

Thanks in advance :)

**Comment by fcisio** [comment]
Hey, personally I haven't had that kind of issue.
The intersection observer works by checking if something is visible in the viewport, regardless of how it comes into the viewport. So Locomotive scroll, should not cause issues.

I also had good results with "loadable", if you have an issue, I believe it could be linked to content jump (images loading in and changing the body height).
You should be able to fix that by setting the right aspect ratio on the images. That way when the image is loaded in it doesn't change the height.

Personally, I use [Cloudinary](https://www.gatsbyjs.com/plugins/gatsby-transformer-cloudinary/?=Cloudinary) for images lazyloading and it's been working great. You should also be able to use [gatsby-images](https://www.gatsbyjs.com/plugins/gatsby-image/).

If you do use the Intersection Observer from 'react-use', you need to modify the condition:
```js
const { rootMargin = '100px', threshold = 0, ...rest } = props

  const ref = useRef(null)
  const intersection = useIntersection(ref, {
    root: null,
    rootMargin: rootMargin,
    threshold: threshold,
  })
  const inView = !!(intersection && intersection.intersectionRatio > threshold)
```
Your issue could also be coming from your ref being passed to a complex component and it not being attached to the right thing. You can test this by adding the ref to a simple div.

**Comment by canadianeagle** [comment]
Thanks so much for the quick response - I'll give your suggestions a shot and let you know how it goes! Thanks!

**Comment by canadianeagle** [comment]
You were right - it was working correctly, but I had a transform-rotated layout so that was messing with it - thanks for the react-use snippet - that came in very handy! Much much thanks.
